
[FILE]

# Folder from which the point cloud files are loaded
pointcloud_folder = pointclouds/

# Folder where the label files will be saved
label_folder = labels/

# Definition file for class names, colors, default class and export format
class_definitions = labels/_classes.json

# Folder from which related images can be loaded (OPTIONAL)
# image_folder = pointclouds/

# Folder with calibration files (OPTIONAL, only required for KITTI format)
# calib_folder = calib/

# Folder where the segmentation labels are saved (OPTIONAL)
# segmentation_folder = labels/segmentation/



[POINTCLOUD]

# Drawing size for points in point cloud (rasterized diameter)
point_size = 6

# Point color for colorless point clouds (r, g, b)
colorless_color = 0.9, 0.9, 0.9

# Colorize colorless point clouds by height value
colorless_colorize = True

# Standard step for point cloud translation (mouse move)
std_translation = 0.003

# Standard step for zooming (mouse scroll)
std_zoom = 0.0025

color_with_label = False

[LABEL]

# Number of decimal places for exporting bounding box parameters
export_precision = 8

# Default bounding box dimensions (picking mode)
std_boundingbox_length = 0.1
std_boundingbox_width  = 0.1
std_boundingbox_height = 0.1

# Standard step for translating bounding box
std_translation = 0.003

# Standard step for rotating bounding box
std_rotation = 0.5

# Standard step for scaling bounding box
std_scaling = 0.0005

# Minimum allowed bounding box dimension
min_boundingbox_dimension = 0.01

# Copy all bounding boxes to next point cloud (forward only)
propagate_labels = False



[USER_INTERFACE]

# Only allow z-rotation (disable for full 6D rotation)
z_rotation_only = False

# Visualize floor (x-y plane) as grid
show_floor = True

# Visualize object orientation as arrow
show_orientation = True

# Background color of viewer (r, g, b)
background_color = 100, 100, 100

# Decimal places shown in UI for active bounding box
viewing_precision = 3

# OpenGL near / far plane
near_plane = 0.1
far_plane  = 300

# Save last perspective when leaving a point cloud
keep_perspective = False

# Show button for related 2D images
show_2d_image = False
